services:
  db:
    container_name: "db"
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
        sleep 5 &&
        python scripts/seed_data.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "${APP_PORT}:8000"

volumes:
  postgres_data: